name: CI

'on':
  push:
    branches:
      - '**' # matches every branch

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [ 12 ]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node_version: ${{ matrix.node_version }}

      - name: run CI
        run: |
          yarn install --ignore-engines
          yarn test
